name: fe-news git submodule update

on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action Submodule Updates
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
